# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.
version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bank
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./initialize/.env.mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - bank-mysql-volume:/var/lib/mysql
      - ./initialize/init.sql:/docker-entrypoint-initdb.d/00-init.sql
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  bank-mysql-volume:

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.
